apiVersion: v1
kind: Secret
metadata:
  name: pos-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "password123"
  JWT_SECRET: "production_ready_secret_key_999"
  DATABASE_URL: "postgresql://postgres:password123@postgres:5432/local_res_db?schema=public"
